services:
  # The Database (PostgreSQL)
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: football-pi
      POSTGRES_DB: fantasy_football
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # The Cache (Redis)
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
