"""create schema represented by main revision 0028

Revision ID: bootstrap_0028
Revises:
Create Date: 2026-08-21 21:18:32.278765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'bootstrap_0028'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_player_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('content_digest', sa.String(length=64), nullable=False),
    sa.Column('total_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unique_player_ids', sa.Integer(), server_default='0', nullable=False),
    sa.Column('deduplicated_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('duplicate_name_keys', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('position_distribution', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('source', sa.String(length=32), server_default='etl_build', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'content_digest', name='uq_snapshot_season_digest')
    )
    op.create_index('ix_canonical_player_snapshot_created', 'canonical_player_snapshots', ['created_at'], unique=False)
    op.create_index('ix_canonical_player_snapshot_season', 'canonical_player_snapshots', ['season'], unique=False)
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('draft_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('current_season', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leagues_current_season'), 'leagues', ['current_season'], unique=False)
    op.create_index(op.f('ix_leagues_id'), 'leagues', ['id'], unique=False)
    op.create_index(op.f('ix_leagues_name'), 'leagues', ['name'], unique=True)
    op.create_table('live_scoring_ingest_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('scoreboard_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('event_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('game_states', sa.JSON(), nullable=True),
    sa.Column('fetch_diagnostics', sa.JSON(), nullable=True),
    sa.Column('raw_response_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'season', 'week', 'scoreboard_fingerprint', name='uq_live_scoring_ingest_event_scope')
    )
    op.create_index('ix_live_scoring_ingest_events_fingerprint', 'live_scoring_ingest_events', ['scoreboard_fingerprint'], unique=False)
    op.create_index(op.f('ix_live_scoring_ingest_events_id'), 'live_scoring_ingest_events', ['id'], unique=False)
    op.create_index('ix_live_scoring_ingest_events_scope', 'live_scoring_ingest_events', ['source', 'season', 'week'], unique=False)
    op.create_table('manager_efficiency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('actual_points_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('optimal_points_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('points_left_on_bench', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('efficiency_rating', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('optimal_lineup_json', sa.JSON(), nullable=True),
    sa.Column('worst_sit_player_name', sa.String(), nullable=True),
    sa.Column('worst_sit_points_diff', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'manager_id', 'season', 'week', name='uq_mgr_eff_league_mgr_season_week')
    )
    op.create_index(op.f('ix_manager_efficiency_id'), 'manager_efficiency', ['id'], unique=False)
    op.create_index(op.f('ix_manager_efficiency_league_id'), 'manager_efficiency', ['league_id'], unique=False)
    op.create_index(op.f('ix_manager_efficiency_manager_id'), 'manager_efficiency', ['manager_id'], unique=False)
    op.create_index(op.f('ix_manager_efficiency_season'), 'manager_efficiency', ['season'], unique=False)
    op.create_index(op.f('ix_manager_efficiency_week'), 'manager_efficiency', ['week'], unique=False)
    op.create_table('nfl_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('kickoff', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nfl_games_event_id'), 'nfl_games', ['event_id'], unique=True)
    op.create_index(op.f('ix_nfl_games_id'), 'nfl_games', ['id'], unique=False)
    op.create_index(op.f('ix_nfl_games_season'), 'nfl_games', ['season'], unique=False)
    op.create_index(op.f('ix_nfl_games_week'), 'nfl_games', ['week'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('nfl_team', sa.String(), nullable=True),
    sa.Column('adp', sa.Float(), nullable=True),
    sa.Column('projected_points', sa.Float(), nullable=True),
    sa.Column('gsis_id', sa.String(), nullable=True),
    sa.Column('espn_id', sa.String(), nullable=True),
    sa.Column('bye_week', sa.Integer(), nullable=True),
    sa.Column('injury_status', sa.String(), nullable=True),
    sa.Column('injury_notes', sa.String(), nullable=True),
    sa.Column('projected_return_date', sa.String(), nullable=True),
    sa.Column('projected_return_week', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('espn_id'),
    sa.UniqueConstraint('gsis_id')
    )
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abbreviation', sa.String(length=8), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation', name='uq_positions_abbreviation')
    )
    op.create_index(op.f('ix_positions_abbreviation'), 'positions', ['abbreviation'], unique=False)
    op.create_index(op.f('ix_positions_id'), 'positions', ['id'], unique=False)
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('token_subject', sa.String(length=255), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti', name='uq_revoked_tokens_jti')
    )
    op.create_index('ix_revoked_tokens_expires_at', 'revoked_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_revoked_tokens_id'), 'revoked_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_revoked_tokens_jti'), 'revoked_tokens', ['jti'], unique=False)
    op.create_table('unmatched_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('scraped_name', sa.String(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unmatched_players_id'), 'unmatched_players', ['id'], unique=False)
    op.create_index(op.f('ix_unmatched_players_scraped_name'), 'unmatched_players', ['scraped_name'], unique=False)
    op.create_index(op.f('ix_unmatched_players_source'), 'unmatched_players', ['source'], unique=False)
    op.create_table('divisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_divisions_id'), 'divisions', ['id'], unique=False)
    op.create_index(op.f('ix_divisions_season'), 'divisions', ['season'], unique=False)
    op.create_table('draft_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('avg_auction_value', sa.Float(), nullable=True),
    sa.Column('median_adp', sa.Float(), nullable=True),
    sa.Column('consensus_tier', sa.String(), nullable=True),
    sa.Column('value_over_replacement', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.String(), nullable=True),
    sa.Column('avg_bid', sa.Float(), nullable=True),
    sa.Column('median_bid', sa.Float(), nullable=True),
    sa.Column('recent_3yr_avg', sa.Float(), nullable=True),
    sa.Column('trend_slope', sa.Float(), nullable=True),
    sa.Column('appearances', sa.Integer(), nullable=True),
    sa.Column('model_score', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', name='uq_draft_value_player_season')
    )
    op.create_index(op.f('ix_draft_values_id'), 'draft_values', ['id'], unique=False)
    op.create_table('keeper_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('max_keepers', sa.Integer(), nullable=True),
    sa.Column('max_years_per_player', sa.Integer(), nullable=True),
    sa.Column('cost_type', sa.String(), nullable=True),
    sa.Column('cost_inflation', sa.Integer(), nullable=True),
    sa.Column('deadline_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('waiver_policy', sa.Boolean(), nullable=True),
    sa.Column('trade_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('drafted_only', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id')
    )
    op.create_index(op.f('ix_keeper_rules_id'), 'keeper_rules', ['id'], unique=False)
    op.create_table('league_mfl_seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('mfl_league_id', sa.String(), nullable=False),
    sa.Column('mfl_franchise_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'season', name='uq_league_mfl_season')
    )
    op.create_index(op.f('ix_league_mfl_seasons_id'), 'league_mfl_seasons', ['id'], unique=False)
    op.create_index(op.f('ix_league_mfl_seasons_league_id'), 'league_mfl_seasons', ['league_id'], unique=False)
    op.create_index(op.f('ix_league_mfl_seasons_season'), 'league_mfl_seasons', ['season'], unique=False)
    op.create_table('league_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('roster_size', sa.Integer(), nullable=True),
    sa.Column('salary_cap', sa.Integer(), nullable=True),
    sa.Column('starting_slots', sa.JSON(), nullable=True),
    sa.Column('waiver_deadline', sa.String(), nullable=True),
    sa.Column('starting_waiver_budget', sa.Integer(), nullable=True),
    sa.Column('waiver_system', sa.String(), nullable=True),
    sa.Column('waiver_tiebreaker', sa.String(), nullable=True),
    sa.Column('trade_deadline', sa.String(), nullable=True),
    sa.Column('trade_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trade_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('allow_playoff_trades', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('require_commissioner_approval', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('trade_veto_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('trade_veto_threshold', sa.Integer(), nullable=True),
    sa.Column('trade_review_period_hours', sa.Integer(), nullable=True),
    sa.Column('trade_max_players_per_side', sa.Integer(), nullable=True),
    sa.Column('trade_league_vote_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('trade_league_vote_threshold', sa.Integer(), nullable=True),
    sa.Column('draft_year', sa.Integer(), nullable=True),
    sa.Column('future_draft_cap', sa.Integer(), nullable=True),
    sa.Column('playoff_qualifiers', sa.Integer(), nullable=True),
    sa.Column('playoff_reseed', sa.Boolean(), nullable=True),
    sa.Column('playoff_consolation', sa.Boolean(), nullable=True),
    sa.Column('playoff_tiebreakers', sa.JSON(), nullable=True),
    sa.Column('divisions_enabled', sa.Boolean(), nullable=True),
    sa.Column('division_count', sa.Integer(), nullable=True),
    sa.Column('division_config_status', sa.String(), nullable=True),
    sa.Column('division_assignment_method', sa.String(), nullable=True),
    sa.Column('division_random_seed', sa.String(), nullable=True),
    sa.Column('division_needs_reseed', sa.Boolean(), nullable=True),
    sa.Column('division_history_enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_league_settings_id'), 'league_settings', ['id'], unique=False)
    op.create_table('manual_player_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('scraped_name', sa.String(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('mapped_at', sa.String(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_player_mappings_id'), 'manual_player_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_manual_player_mappings_scraped_name'), 'manual_player_mappings', ['scraped_name'], unique=False)
    op.create_index(op.f('ix_manual_player_mappings_source'), 'manual_player_mappings', ['source'], unique=False)
    op.create_table('mfl_html_record_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_key', sa.String(length=80), nullable=False),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('target_league_id', sa.Integer(), nullable=True),
    sa.Column('league_id', sa.String(length=32), nullable=True),
    sa.Column('source_endpoint', sa.String(length=80), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('extracted_at_utc', sa.String(), nullable=True),
    sa.Column('normalization_version', sa.String(length=16), nullable=False),
    sa.Column('row_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('record_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_key', 'row_fingerprint', name='uq_mfl_html_record_fact_dataset_fingerprint')
    )
    op.create_index('ix_mfl_html_record_fact_dataset', 'mfl_html_record_facts', ['dataset_key'], unique=False)
    op.create_index('ix_mfl_html_record_fact_league', 'mfl_html_record_facts', ['league_id'], unique=False)
    op.create_index('ix_mfl_html_record_fact_season', 'mfl_html_record_facts', ['season'], unique=False)
    op.create_index('ix_mfl_html_record_fact_target_league', 'mfl_html_record_facts', ['target_league_id'], unique=False)
    op.create_index(op.f('ix_mfl_html_record_facts_id'), 'mfl_html_record_facts', ['id'], unique=False)
    op.create_table('mfl_ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_stage', sa.String(length=32), nullable=False),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('target_league_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('truncate_before_load', sa.Boolean(), nullable=False),
    sa.Column('input_roots', sa.JSON(), nullable=False),
    sa.Column('command', sa.String(), nullable=True),
    sa.Column('git_sha', sa.String(length=64), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['target_league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mfl_ingestion_run_stage', 'mfl_ingestion_runs', ['pipeline_stage'], unique=False)
    op.create_index('ix_mfl_ingestion_run_status', 'mfl_ingestion_runs', ['status'], unique=False)
    op.create_index('ix_mfl_ingestion_run_target_league', 'mfl_ingestion_runs', ['target_league_id'], unique=False)
    op.create_index(op.f('ix_mfl_ingestion_runs_id'), 'mfl_ingestion_runs', ['id'], unique=False)
    op.create_table('platform_projections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('projected_points', sa.Float(), nullable=True),
    sa.Column('adp', sa.Float(), nullable=True),
    sa.Column('auction_value', sa.Float(), nullable=True),
    sa.Column('position_rank', sa.Integer(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_projections_id'), 'platform_projections', ['id'], unique=False)
    op.create_table('player_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('alias_name', sa.String(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'alias_name', 'source', name='uq_player_alias_source')
    )
    op.create_index(op.f('ix_player_aliases_alias_name'), 'player_aliases', ['alias_name'], unique=False)
    op.create_index(op.f('ix_player_aliases_id'), 'player_aliases', ['id'], unique=False)
    op.create_table('player_id_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('yahoo_id', sa.String(), nullable=True),
    sa.Column('espn_id', sa.String(), nullable=True),
    sa.Column('draftsharks_id', sa.String(), nullable=True),
    sa.Column('fantasypros_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_id_mappings_id'), 'player_id_mappings', ['id'], unique=False)
    op.create_table('player_news_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_item_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sa.String(length=32), nullable=True),
    sa.Column('sentiment_tags', sa.JSON(), nullable=True),
    sa.Column('meta_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'source', 'source_item_id', name='uq_player_news_league_source_item')
    )
    op.create_index(op.f('ix_player_news_items_id'), 'player_news_items', ['id'], unique=False)
    op.create_index(op.f('ix_player_news_items_league_id'), 'player_news_items', ['league_id'], unique=False)
    op.create_index(op.f('ix_player_news_items_published_at'), 'player_news_items', ['published_at'], unique=False)
    op.create_index('ix_player_news_league_published', 'player_news_items', ['league_id', 'published_at'], unique=False)
    op.create_index('ix_player_news_published', 'player_news_items', ['published_at'], unique=False)
    op.create_table('player_news_sentiment_trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('window_hours', sa.Integer(), nullable=False),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.Column('mention_count', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'player_id', 'window_hours', name='uq_news_trend_window')
    )
    op.create_index('ix_news_trend_league_player', 'player_news_sentiment_trends', ['league_id', 'player_id'], unique=False)
    op.create_index(op.f('ix_player_news_sentiment_trends_id'), 'player_news_sentiment_trends', ['id'], unique=False)
    op.create_index(op.f('ix_player_news_sentiment_trends_league_id'), 'player_news_sentiment_trends', ['league_id'], unique=False)
    op.create_index(op.f('ix_player_news_sentiment_trends_player_id'), 'player_news_sentiment_trends', ['player_id'], unique=False)
    op.create_table('player_seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('nfl_team', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('bye_week', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', name='uq_player_season')
    )
    op.create_index(op.f('ix_player_seasons_id'), 'player_seasons', ['id'], unique=False)
    op.create_index(op.f('ix_player_seasons_season'), 'player_seasons', ['season'], unique=False)
    op.create_table('player_weekly_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('fantasy_points', sa.Float(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', 'week', 'source', name='uq_player_week_source')
    )
    op.create_index(op.f('ix_player_weekly_stats_id'), 'player_weekly_stats', ['id'], unique=False)
    op.create_index(op.f('ix_player_weekly_stats_season'), 'player_weekly_stats', ['season'], unique=False)
    op.create_index(op.f('ix_player_weekly_stats_week'), 'player_weekly_stats', ['week'], unique=False)
    op.create_table('playoff_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playoff_snapshots_id'), 'playoff_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_playoff_snapshots_season'), 'playoff_snapshots', ['season'], unique=False)
    op.create_table('validated_draft_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('winning_bid', sa.Float(), nullable=True),
    sa.Column('is_keeper', sa.Boolean(), nullable=False),
    sa.Column('etl_version', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'season_year', 'owner_id', 'player_id', name='uq_validated_draft_results_pick')
    )
    op.create_index(op.f('ix_validated_draft_results_id'), 'validated_draft_results', ['id'], unique=False)
    op.create_index('ix_validated_draft_results_league_season', 'validated_draft_results', ['league_id', 'season_year'], unique=False)
    op.create_index('ix_validated_draft_results_player', 'validated_draft_results', ['player_id'], unique=False)
    op.create_table('mfl_ingestion_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('dataset_key', sa.String(length=80), nullable=False),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('source_league_id', sa.String(length=32), nullable=True),
    sa.Column('relative_path', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('retention_class', sa.String(length=32), nullable=True),
    sa.Column('archived_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['mfl_ingestion_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'relative_path', name='uq_mfl_ingestion_file_run_path')
    )
    op.create_index('ix_mfl_ingestion_file_dataset', 'mfl_ingestion_files', ['dataset_key'], unique=False)
    op.create_index('ix_mfl_ingestion_file_run', 'mfl_ingestion_files', ['run_id'], unique=False)
    op.create_index('ix_mfl_ingestion_file_source_league', 'mfl_ingestion_files', ['source_league_id'], unique=False)
    op.create_index(op.f('ix_mfl_ingestion_files_id'), 'mfl_ingestion_files', ['id'], unique=False)
    op.create_table('player_news_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_item_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('match_reason', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['news_item_id'], ['player_news_items.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('news_item_id', 'player_id', name='uq_player_news_player_link')
    )
    op.create_index('ix_player_news_link_player', 'player_news_links', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_news_links_id'), 'player_news_links', ['id'], unique=False)
    op.create_index(op.f('ix_player_news_links_news_item_id'), 'player_news_links', ['news_item_id'], unique=False)
    op.create_index(op.f('ix_player_news_links_player_id'), 'player_news_links', ['player_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_commissioner', sa.Boolean(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.Column('future_draft_budget', sa.Integer(), nullable=True),
    sa.Column('team_logo_url', sa.String(), nullable=True),
    sa.Column('team_color_primary', sa.String(), nullable=True),
    sa.Column('team_color_secondary', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_username', sa.String(length=255), nullable=False),
    sa.Column('actor_is_superuser', sa.Boolean(), nullable=False),
    sa.Column('actor_is_commissioner', sa.Boolean(), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=128), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admin_audit_logs_actor_user_id', 'admin_audit_logs', ['actor_user_id'], unique=False)
    op.create_index('ix_admin_audit_logs_created_at', 'admin_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_id'), 'admin_audit_logs', ['id'], unique=False)
    op.create_table('bug_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('page_name', sa.String(), nullable=True),
    sa.Column('issue_type', sa.String(), nullable=True),
    sa.Column('page_url', sa.String(), nullable=True),
    sa.Column('github_issue_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bug_reports_id'), 'bug_reports', ['id'], unique=False)
    op.create_table('division_config_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assignment_method', sa.String(), nullable=True),
    sa.Column('random_seed', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('imbalance_pct', sa.Float(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_division_config_snapshots_id'), 'division_config_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_division_config_snapshots_league_id'), 'division_config_snapshots', ['league_id'], unique=False)
    op.create_index(op.f('ix_division_config_snapshots_season'), 'division_config_snapshots', ['season'], unique=False)
    op.create_table('division_name_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('division_name', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reported_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['reported_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_division_name_reports_id'), 'division_name_reports', ['id'], unique=False)
    op.create_index(op.f('ix_division_name_reports_league_id'), 'division_name_reports', ['league_id'], unique=False)
    op.create_index(op.f('ix_division_name_reports_season'), 'division_name_reports', ['season'], unique=False)
    op.create_table('draft_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('total_budget', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'owner_id', 'year', name='uq_budget_league_owner_year')
    )
    op.create_index(op.f('ix_draft_budgets_id'), 'draft_budgets', ['id'], unique=False)
    op.create_index(op.f('ix_draft_budgets_year'), 'draft_budgets', ['year'], unique=False)
    op.create_table('draft_picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('round_num', sa.Integer(), nullable=True),
    sa.Column('pick_num', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('current_status', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('is_taxi', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_picks_id'), 'draft_picks', ['id'], unique=False)
    op.create_table('economic_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=True),
    sa.Column('currency_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('from_owner_id', sa.Integer(), nullable=True),
    sa.Column('to_owner_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('reference_type', sa.String(), nullable=True),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['to_owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_economic_ledger_created_at'), 'economic_ledger', ['created_at'], unique=False)
    op.create_index(op.f('ix_economic_ledger_created_by_user_id'), 'economic_ledger', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_economic_ledger_currency_type'), 'economic_ledger', ['currency_type'], unique=False)
    op.create_index(op.f('ix_economic_ledger_from_owner_id'), 'economic_ledger', ['from_owner_id'], unique=False)
    op.create_index(op.f('ix_economic_ledger_id'), 'economic_ledger', ['id'], unique=False)
    op.create_index(op.f('ix_economic_ledger_league_id'), 'economic_ledger', ['league_id'], unique=False)
    op.create_index('ix_economic_ledger_owner_lookup', 'economic_ledger', ['league_id', 'currency_type', 'season_year', 'to_owner_id', 'from_owner_id'], unique=False)
    op.create_index('ix_economic_ledger_reference', 'economic_ledger', ['reference_type', 'reference_id'], unique=False)
    op.create_index(op.f('ix_economic_ledger_reference_id'), 'economic_ledger', ['reference_id'], unique=False)
    op.create_index(op.f('ix_economic_ledger_reference_type'), 'economic_ledger', ['reference_type'], unique=False)
    op.create_index(op.f('ix_economic_ledger_season_year'), 'economic_ledger', ['season_year'], unique=False)
    op.create_index(op.f('ix_economic_ledger_to_owner_id'), 'economic_ledger', ['to_owner_id'], unique=False)
    op.create_index(op.f('ix_economic_ledger_transaction_type'), 'economic_ledger', ['transaction_type'], unique=False)
    op.create_table('keepers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('keep_cost', sa.Numeric(), nullable=False),
    sa.Column('years_kept_count', sa.Integer(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_commish', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('flag_waiver', sa.Boolean(), nullable=True),
    sa.Column('flag_trade', sa.Boolean(), nullable=True),
    sa.Column('flag_drop', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keepers_id'), 'keepers', ['id'], unique=False)
    op.create_table('league_history_team_owner_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=160), nullable=False),
    sa.Column('team_name_key', sa.String(length=160), nullable=False),
    sa.Column('owner_name', sa.String(length=160), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'season', 'team_name_key', name='uq_league_history_team_owner_map_key')
    )
    op.create_index(op.f('ix_league_history_team_owner_map_id'), 'league_history_team_owner_map', ['id'], unique=False)
    op.create_index('ix_league_history_team_owner_map_league', 'league_history_team_owner_map', ['league_id'], unique=False)
    op.create_index('ix_league_history_team_owner_map_season', 'league_history_team_owner_map', ['season'], unique=False)
    op.create_index('ix_league_history_team_owner_map_team_key', 'league_history_team_owner_map', ['team_name_key'], unique=False)
    op.create_table('lineup_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lineup_submissions_id'), 'lineup_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_lineup_submissions_season'), 'lineup_submissions', ['season'], unique=False)
    op.create_index(op.f('ix_lineup_submissions_week'), 'lineup_submissions', ['week'], unique=False)
    op.create_table('matchups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('home_score', sa.Float(), nullable=True),
    sa.Column('away_score', sa.Float(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('game_status', sa.String(), nullable=True),
    sa.Column('is_playoff', sa.Boolean(), nullable=False),
    sa.Column('is_division_matchup', sa.Boolean(), nullable=True),
    sa.Column('is_rivalry_week', sa.Boolean(), nullable=True),
    sa.Column('rivalry_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matchups_id'), 'matchups', ['id'], unique=False)
    op.create_index(op.f('ix_matchups_season'), 'matchups', ['season'], unique=False)
    op.create_index(op.f('ix_matchups_week'), 'matchups', ['week'], unique=False)
    op.create_index('uix_matchups_league_season_week_home_away', 'matchups', ['league_id', 'season', 'week', 'home_team_id', 'away_team_id'], unique=True, postgresql_where=sa.text('season IS NOT NULL'))
    op.create_table('owner_season_behaviors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('starting_budget', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_spend', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('remaining_budget', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('budget_source', sa.String(length=32), nullable=True),
    sa.Column('overspent', sa.Boolean(), nullable=True),
    sa.Column('spend_by_position', sa.JSON(), nullable=True),
    sa.Column('pick_count_by_position', sa.JSON(), nullable=True),
    sa.Column('position_spend_pct', sa.JSON(), nullable=True),
    sa.Column('max_bid_by_position', sa.JSON(), nullable=True),
    sa.Column('avg_bid_by_position', sa.JSON(), nullable=True),
    sa.Column('aggressiveness_index', sa.Float(), nullable=True),
    sa.Column('positional_bias_index', sa.Float(), nullable=True),
    sa.Column('etl_version', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'owner_id', 'season_year', name='uq_osb_league_owner_season')
    )
    op.create_index('ix_osb_league_season', 'owner_season_behaviors', ['league_id', 'season_year'], unique=False)
    op.create_index(op.f('ix_owner_season_behaviors_id'), 'owner_season_behaviors', ['id'], unique=False)
    op.create_index(op.f('ix_owner_season_behaviors_season_year'), 'owner_season_behaviors', ['season_year'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_ip', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_password_reset_token_expires', 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index('ix_password_reset_token_user', 'password_reset_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_expires_at'), 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('playoff_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('match_id', sa.String(), nullable=True),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('team_1_id', sa.Integer(), nullable=True),
    sa.Column('team_2_id', sa.Integer(), nullable=True),
    sa.Column('team_1_score', sa.Float(), nullable=True),
    sa.Column('team_2_score', sa.Float(), nullable=True),
    sa.Column('is_bye', sa.Boolean(), nullable=True),
    sa.Column('winner_to', sa.String(), nullable=True),
    sa.Column('team_1_seed', sa.Integer(), nullable=True),
    sa.Column('team_2_seed', sa.Integer(), nullable=True),
    sa.Column('team_1_is_division_winner', sa.Boolean(), nullable=True),
    sa.Column('team_2_is_division_winner', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['team_1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_2_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playoff_matches_id'), 'playoff_matches', ['id'], unique=False)
    op.create_index(op.f('ix_playoff_matches_match_id'), 'playoff_matches', ['match_id'], unique=False)
    op.create_index(op.f('ix_playoff_matches_season'), 'playoff_matches', ['season'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rotated_from_token_hash', sa.String(length=128), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_refresh_tokens_token_hash')
    )
    op.create_index('ix_refresh_tokens_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('scoring_rule_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('proposed_change', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('proposed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('voting_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalized_by_user_id', sa.Integer(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finalized_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['proposed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoring_rule_proposals_id'), 'scoring_rule_proposals', ['id'], unique=False)
    op.create_index('ix_scoring_rule_proposals_lookup', 'scoring_rule_proposals', ['league_id', 'season_year', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_scoring_rule_proposals_season_year'), 'scoring_rule_proposals', ['season_year'], unique=False)
    op.create_table('scoring_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('source_platform', sa.String(length=32), nullable=False),
    sa.Column('is_system_template', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'name', 'season_year', name='uq_scoring_template_league_name_season')
    )
    op.create_index(op.f('ix_scoring_templates_id'), 'scoring_templates', ['id'], unique=False)
    op.create_index('ix_scoring_templates_lookup', 'scoring_templates', ['league_id', 'season_year', 'is_active'], unique=False)
    op.create_index(op.f('ix_scoring_templates_season_year'), 'scoring_templates', ['season_year'], unique=False)
    op.create_table('site_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('referrer', sa.String(), nullable=True),
    sa.Column('client_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_visits_id'), 'site_visits', ['id'], unique=False)
    op.create_index(op.f('ix_site_visits_path'), 'site_visits', ['path'], unique=False)
    op.create_index(op.f('ix_site_visits_session_id'), 'site_visits', ['session_id'], unique=False)
    op.create_index(op.f('ix_site_visits_timestamp'), 'site_visits', ['timestamp'], unique=False)
    op.create_index(op.f('ix_site_visits_user_id'), 'site_visits', ['user_id'], unique=False)
    op.create_table('trade_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('offered_player_id', sa.Integer(), nullable=False),
    sa.Column('requested_player_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('offered_dollars', sa.Numeric(), nullable=True),
    sa.Column('requested_dollars', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['offered_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['requested_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_proposals_id'), 'trade_proposals', ['id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('team_a_id', sa.Integer(), nullable=False),
    sa.Column('team_b_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('commissioner_comments', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['team_a_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_b_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_created_by_user_id'), 'trades', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_index(op.f('ix_trades_league_id'), 'trades', ['league_id'], unique=False)
    op.create_index('ix_trades_league_status', 'trades', ['league_id', 'status'], unique=False)
    op.create_index(op.f('ix_trades_status'), 'trades', ['status'], unique=False)
    op.create_index('ix_trades_submitted_at', 'trades', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_trades_team_a_id'), 'trades', ['team_a_id'], unique=False)
    op.create_index(op.f('ix_trades_team_b_id'), 'trades', ['team_b_id'], unique=False)
    op.create_index('ix_trades_teams', 'trades', ['team_a_id', 'team_b_id'], unique=False)
    op.create_table('transaction_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('old_owner_id', sa.Integer(), nullable=True),
    sa.Column('new_owner_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['new_owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['old_owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_history_id'), 'transaction_history', ['id'], unique=False)
    op.create_index(op.f('ix_transaction_history_season'), 'transaction_history', ['season'], unique=False)
    op.create_table('waiver_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('starting_budget', sa.Integer(), nullable=True),
    sa.Column('remaining_budget', sa.Integer(), nullable=True),
    sa.Column('spent_budget', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('total_budget', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'owner_id', name='uq_waiver_league_owner')
    )
    op.create_index(op.f('ix_waiver_budgets_id'), 'waiver_budgets', ['id'], unique=False)
    op.create_index(op.f('ix_waiver_budgets_year'), 'waiver_budgets', ['year'], unique=False)
    op.create_table('waiver_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('drop_player_id', sa.Integer(), nullable=True),
    sa.Column('bid_amount', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['drop_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waiver_claims_id'), 'waiver_claims', ['id'], unique=False)
    op.create_table('scoring_rule_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('voter_user_id', sa.Integer(), nullable=False),
    sa.Column('vote', sa.String(length=16), nullable=False),
    sa.Column('vote_weight', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('voted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['scoring_rule_proposals.id'], ),
    sa.ForeignKeyConstraint(['voter_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id', 'voter_user_id', name='uq_scoring_rule_votes_proposal_voter')
    )
    op.create_index(op.f('ix_scoring_rule_votes_id'), 'scoring_rule_votes', ['id'], unique=False)
    op.create_table('scoring_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('range_min', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('range_max', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('point_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('calculation_type', sa.String(), nullable=False),
    sa.Column('applicable_positions', sa.JSON(), nullable=False),
    sa.Column('position_ids', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['scoring_templates.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoring_rules_id'), 'scoring_rules', ['id'], unique=False)
    op.create_index('ix_scoring_rules_lookup', 'scoring_rules', ['league_id', 'season_year', 'is_active', 'event_name'], unique=False)
    op.create_index(op.f('ix_scoring_rules_season_year'), 'scoring_rules', ['season_year'], unique=False)
    op.create_table('trade_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('asset_side', sa.String(length=1), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('draft_pick_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('season_year', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['draft_pick_id'], ['draft_picks.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trade_assets_draft_pick', 'trade_assets', ['draft_pick_id'], unique=False)
    op.create_index(op.f('ix_trade_assets_id'), 'trade_assets', ['id'], unique=False)
    op.create_index('ix_trade_assets_player', 'trade_assets', ['player_id'], unique=False)
    op.create_index(op.f('ix_trade_assets_trade_id'), 'trade_assets', ['trade_id'], unique=False)
    op.create_index('ix_trade_assets_trade_side', 'trade_assets', ['trade_id', 'asset_side'], unique=False)
    op.create_index('ix_trade_assets_type', 'trade_assets', ['asset_type'], unique=False)
    op.create_table('trade_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_events_actor_user_id'), 'trade_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_trade_events_id'), 'trade_events', ['id'], unique=False)
    op.create_index('ix_trade_events_trade_created', 'trade_events', ['trade_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_trade_events_trade_id'), 'trade_events', ['trade_id'], unique=False)
    op.create_index('ix_trade_events_type', 'trade_events', ['event_type'], unique=False)
    op.create_table('scoring_rule_change_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('scoring_rule_id', sa.Integer(), nullable=True),
    sa.Column('season_year', sa.Integer(), nullable=True),
    sa.Column('change_type', sa.String(length=32), nullable=False),
    sa.Column('rationale', sa.String(), nullable=True),
    sa.Column('previous_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['scoring_rule_id'], ['scoring_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoring_rule_change_logs_id'), 'scoring_rule_change_logs', ['id'], unique=False)
    op.create_index('ix_scoring_rule_change_logs_lookup', 'scoring_rule_change_logs', ['league_id', 'season_year', 'changed_at'], unique=False)
    op.create_index(op.f('ix_scoring_rule_change_logs_season_year'), 'scoring_rule_change_logs', ['season_year'], unique=False)
    op.create_table('scoring_template_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('scoring_rule_id', sa.Integer(), nullable=False),
    sa.Column('rule_order', sa.Integer(), nullable=False),
    sa.Column('included', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scoring_rule_id'], ['scoring_rules.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['scoring_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'scoring_rule_id', name='uq_scoring_template_rule_link')
    )
    op.create_index(op.f('ix_scoring_template_rules_id'), 'scoring_template_rules', ['id'], unique=False)
    op.create_index('ix_scoring_template_rules_template_order', 'scoring_template_rules', ['template_id', 'rule_order'], unique=False)
    op.execute(
        """
        CREATE INDEX idx_scoring_positions
        ON scoring_rules
        USING gin ((applicable_positions::jsonb))
        """
    )
    op.execute(
        """
        CREATE VIEW league_efficiency_leaderboard AS
        SELECT
            manager_id,
            league_id,
            COUNT(week) AS weeks_played,
            SUM(actual_points_total) AS total_actual,
            SUM(optimal_points_total) AS total_optimal,
            ROUND(AVG(actual_points_total / NULLIF(optimal_points_total, 0)), 4) AS avg_efficiency,
            SUM(points_left_on_bench) AS total_points_lost
        FROM manager_efficiency
        GROUP BY manager_id, league_id
        ORDER BY avg_efficiency DESC
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS league_efficiency_leaderboard")
    op.execute("DROP INDEX IF EXISTS idx_scoring_positions")
    op.drop_index('ix_scoring_template_rules_template_order', table_name='scoring_template_rules')
    op.drop_index(op.f('ix_scoring_template_rules_id'), table_name='scoring_template_rules')
    op.drop_table('scoring_template_rules')
    op.drop_index(op.f('ix_scoring_rule_change_logs_season_year'), table_name='scoring_rule_change_logs')
    op.drop_index('ix_scoring_rule_change_logs_lookup', table_name='scoring_rule_change_logs')
    op.drop_index(op.f('ix_scoring_rule_change_logs_id'), table_name='scoring_rule_change_logs')
    op.drop_table('scoring_rule_change_logs')
    op.drop_index('ix_trade_events_type', table_name='trade_events')
    op.drop_index(op.f('ix_trade_events_trade_id'), table_name='trade_events')
    op.drop_index('ix_trade_events_trade_created', table_name='trade_events')
    op.drop_index(op.f('ix_trade_events_id'), table_name='trade_events')
    op.drop_index(op.f('ix_trade_events_actor_user_id'), table_name='trade_events')
    op.drop_table('trade_events')
    op.drop_index('ix_trade_assets_type', table_name='trade_assets')
    op.drop_index('ix_trade_assets_trade_side', table_name='trade_assets')
    op.drop_index(op.f('ix_trade_assets_trade_id'), table_name='trade_assets')
    op.drop_index('ix_trade_assets_player', table_name='trade_assets')
    op.drop_index(op.f('ix_trade_assets_id'), table_name='trade_assets')
    op.drop_index('ix_trade_assets_draft_pick', table_name='trade_assets')
    op.drop_table('trade_assets')
    op.drop_index(op.f('ix_scoring_rules_season_year'), table_name='scoring_rules')
    op.drop_index('ix_scoring_rules_lookup', table_name='scoring_rules')
    op.drop_index(op.f('ix_scoring_rules_id'), table_name='scoring_rules')
    op.drop_table('scoring_rules')
    op.drop_index(op.f('ix_scoring_rule_votes_id'), table_name='scoring_rule_votes')
    op.drop_table('scoring_rule_votes')
    op.drop_index(op.f('ix_waiver_claims_id'), table_name='waiver_claims')
    op.drop_table('waiver_claims')
    op.drop_index(op.f('ix_waiver_budgets_year'), table_name='waiver_budgets')
    op.drop_index(op.f('ix_waiver_budgets_id'), table_name='waiver_budgets')
    op.drop_table('waiver_budgets')
    op.drop_index(op.f('ix_transaction_history_season'), table_name='transaction_history')
    op.drop_index(op.f('ix_transaction_history_id'), table_name='transaction_history')
    op.drop_table('transaction_history')
    op.drop_index('ix_trades_teams', table_name='trades')
    op.drop_index(op.f('ix_trades_team_b_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_team_a_id'), table_name='trades')
    op.drop_index('ix_trades_submitted_at', table_name='trades')
    op.drop_index(op.f('ix_trades_status'), table_name='trades')
    op.drop_index('ix_trades_league_status', table_name='trades')
    op.drop_index(op.f('ix_trades_league_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_created_by_user_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_trade_proposals_id'), table_name='trade_proposals')
    op.drop_table('trade_proposals')
    op.drop_index(op.f('ix_site_visits_user_id'), table_name='site_visits')
    op.drop_index(op.f('ix_site_visits_timestamp'), table_name='site_visits')
    op.drop_index(op.f('ix_site_visits_session_id'), table_name='site_visits')
    op.drop_index(op.f('ix_site_visits_path'), table_name='site_visits')
    op.drop_index(op.f('ix_site_visits_id'), table_name='site_visits')
    op.drop_table('site_visits')
    op.drop_index(op.f('ix_scoring_templates_season_year'), table_name='scoring_templates')
    op.drop_index('ix_scoring_templates_lookup', table_name='scoring_templates')
    op.drop_index(op.f('ix_scoring_templates_id'), table_name='scoring_templates')
    op.drop_table('scoring_templates')
    op.drop_index(op.f('ix_scoring_rule_proposals_season_year'), table_name='scoring_rule_proposals')
    op.drop_index('ix_scoring_rule_proposals_lookup', table_name='scoring_rule_proposals')
    op.drop_index(op.f('ix_scoring_rule_proposals_id'), table_name='scoring_rule_proposals')
    op.drop_table('scoring_rule_proposals')
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_expires_at', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_playoff_matches_season'), table_name='playoff_matches')
    op.drop_index(op.f('ix_playoff_matches_match_id'), table_name='playoff_matches')
    op.drop_index(op.f('ix_playoff_matches_id'), table_name='playoff_matches')
    op.drop_table('playoff_matches')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_expires_at'), table_name='password_reset_tokens')
    op.drop_index('ix_password_reset_token_user', table_name='password_reset_tokens')
    op.drop_index('ix_password_reset_token_expires', table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_owner_season_behaviors_season_year'), table_name='owner_season_behaviors')
    op.drop_index(op.f('ix_owner_season_behaviors_id'), table_name='owner_season_behaviors')
    op.drop_index('ix_osb_league_season', table_name='owner_season_behaviors')
    op.drop_table('owner_season_behaviors')
    op.drop_index('uix_matchups_league_season_week_home_away', table_name='matchups')
    op.drop_index(op.f('ix_matchups_week'), table_name='matchups')
    op.drop_index(op.f('ix_matchups_season'), table_name='matchups')
    op.drop_index(op.f('ix_matchups_id'), table_name='matchups')
    op.drop_table('matchups')
    op.drop_index(op.f('ix_lineup_submissions_week'), table_name='lineup_submissions')
    op.drop_index(op.f('ix_lineup_submissions_season'), table_name='lineup_submissions')
    op.drop_index(op.f('ix_lineup_submissions_id'), table_name='lineup_submissions')
    op.drop_table('lineup_submissions')
    op.drop_index('ix_league_history_team_owner_map_team_key', table_name='league_history_team_owner_map')
    op.drop_index('ix_league_history_team_owner_map_season', table_name='league_history_team_owner_map')
    op.drop_index('ix_league_history_team_owner_map_league', table_name='league_history_team_owner_map')
    op.drop_index(op.f('ix_league_history_team_owner_map_id'), table_name='league_history_team_owner_map')
    op.drop_table('league_history_team_owner_map')
    op.drop_index(op.f('ix_keepers_id'), table_name='keepers')
    op.drop_table('keepers')
    op.drop_index(op.f('ix_economic_ledger_transaction_type'), table_name='economic_ledger')
    op.drop_index(op.f('ix_economic_ledger_to_owner_id'), table_name='economic_ledger')
    op.drop_index(op.f('ix_economic_ledger_season_year'), table_name='economic_ledger')
    op.drop_index(op.f('ix_economic_ledger_reference_type'), table_name='economic_ledger')
    op.drop_index(op.f('ix_economic_ledger_reference_id'), table_name='economic_ledger')
    op.drop_index('ix_economic_ledger_reference', table_name='economic_ledger')
    op.drop_index('ix_economic_ledger_owner_lookup', table_name='economic_ledger')
    op.drop_index(op.f('ix_economic_ledger_league_id'), table_name='economic_ledger')
    op.drop_index(op.f('ix_economic_ledger_id'), table_name='economic_ledger')
    op.drop_index(op.f('ix_economic_ledger_from_owner_id'), table_name='economic_ledger')
    op.drop_index(op.f('ix_economic_ledger_currency_type'), table_name='economic_ledger')
    op.drop_index(op.f('ix_economic_ledger_created_by_user_id'), table_name='economic_ledger')
    op.drop_index(op.f('ix_economic_ledger_created_at'), table_name='economic_ledger')
    op.drop_table('economic_ledger')
    op.drop_index(op.f('ix_draft_picks_id'), table_name='draft_picks')
    op.drop_table('draft_picks')
    op.drop_index(op.f('ix_draft_budgets_year'), table_name='draft_budgets')
    op.drop_index(op.f('ix_draft_budgets_id'), table_name='draft_budgets')
    op.drop_table('draft_budgets')
    op.drop_index(op.f('ix_division_name_reports_season'), table_name='division_name_reports')
    op.drop_index(op.f('ix_division_name_reports_league_id'), table_name='division_name_reports')
    op.drop_index(op.f('ix_division_name_reports_id'), table_name='division_name_reports')
    op.drop_table('division_name_reports')
    op.drop_index(op.f('ix_division_config_snapshots_season'), table_name='division_config_snapshots')
    op.drop_index(op.f('ix_division_config_snapshots_league_id'), table_name='division_config_snapshots')
    op.drop_index(op.f('ix_division_config_snapshots_id'), table_name='division_config_snapshots')
    op.drop_table('division_config_snapshots')
    op.drop_index(op.f('ix_bug_reports_id'), table_name='bug_reports')
    op.drop_table('bug_reports')
    op.drop_index(op.f('ix_admin_audit_logs_id'), table_name='admin_audit_logs')
    op.drop_index('ix_admin_audit_logs_created_at', table_name='admin_audit_logs')
    op.drop_index('ix_admin_audit_logs_actor_user_id', table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_player_news_links_player_id'), table_name='player_news_links')
    op.drop_index(op.f('ix_player_news_links_news_item_id'), table_name='player_news_links')
    op.drop_index(op.f('ix_player_news_links_id'), table_name='player_news_links')
    op.drop_index('ix_player_news_link_player', table_name='player_news_links')
    op.drop_table('player_news_links')
    op.drop_index(op.f('ix_mfl_ingestion_files_id'), table_name='mfl_ingestion_files')
    op.drop_index('ix_mfl_ingestion_file_source_league', table_name='mfl_ingestion_files')
    op.drop_index('ix_mfl_ingestion_file_run', table_name='mfl_ingestion_files')
    op.drop_index('ix_mfl_ingestion_file_dataset', table_name='mfl_ingestion_files')
    op.drop_table('mfl_ingestion_files')
    op.drop_index('ix_validated_draft_results_player', table_name='validated_draft_results')
    op.drop_index('ix_validated_draft_results_league_season', table_name='validated_draft_results')
    op.drop_index(op.f('ix_validated_draft_results_id'), table_name='validated_draft_results')
    op.drop_table('validated_draft_results')
    op.drop_index(op.f('ix_playoff_snapshots_season'), table_name='playoff_snapshots')
    op.drop_index(op.f('ix_playoff_snapshots_id'), table_name='playoff_snapshots')
    op.drop_table('playoff_snapshots')
    op.drop_index(op.f('ix_player_weekly_stats_week'), table_name='player_weekly_stats')
    op.drop_index(op.f('ix_player_weekly_stats_season'), table_name='player_weekly_stats')
    op.drop_index(op.f('ix_player_weekly_stats_id'), table_name='player_weekly_stats')
    op.drop_table('player_weekly_stats')
    op.drop_index(op.f('ix_player_seasons_season'), table_name='player_seasons')
    op.drop_index(op.f('ix_player_seasons_id'), table_name='player_seasons')
    op.drop_table('player_seasons')
    op.drop_index(op.f('ix_player_news_sentiment_trends_player_id'), table_name='player_news_sentiment_trends')
    op.drop_index(op.f('ix_player_news_sentiment_trends_league_id'), table_name='player_news_sentiment_trends')
    op.drop_index(op.f('ix_player_news_sentiment_trends_id'), table_name='player_news_sentiment_trends')
    op.drop_index('ix_news_trend_league_player', table_name='player_news_sentiment_trends')
    op.drop_table('player_news_sentiment_trends')
    op.drop_index('ix_player_news_published', table_name='player_news_items')
    op.drop_index('ix_player_news_league_published', table_name='player_news_items')
    op.drop_index(op.f('ix_player_news_items_published_at'), table_name='player_news_items')
    op.drop_index(op.f('ix_player_news_items_league_id'), table_name='player_news_items')
    op.drop_index(op.f('ix_player_news_items_id'), table_name='player_news_items')
    op.drop_table('player_news_items')
    op.drop_index(op.f('ix_player_id_mappings_id'), table_name='player_id_mappings')
    op.drop_table('player_id_mappings')
    op.drop_index(op.f('ix_player_aliases_id'), table_name='player_aliases')
    op.drop_index(op.f('ix_player_aliases_alias_name'), table_name='player_aliases')
    op.drop_table('player_aliases')
    op.drop_index(op.f('ix_platform_projections_id'), table_name='platform_projections')
    op.drop_table('platform_projections')
    op.drop_index(op.f('ix_mfl_ingestion_runs_id'), table_name='mfl_ingestion_runs')
    op.drop_index('ix_mfl_ingestion_run_target_league', table_name='mfl_ingestion_runs')
    op.drop_index('ix_mfl_ingestion_run_status', table_name='mfl_ingestion_runs')
    op.drop_index('ix_mfl_ingestion_run_stage', table_name='mfl_ingestion_runs')
    op.drop_table('mfl_ingestion_runs')
    op.drop_index(op.f('ix_mfl_html_record_facts_id'), table_name='mfl_html_record_facts')
    op.drop_index('ix_mfl_html_record_fact_target_league', table_name='mfl_html_record_facts')
    op.drop_index('ix_mfl_html_record_fact_season', table_name='mfl_html_record_facts')
    op.drop_index('ix_mfl_html_record_fact_league', table_name='mfl_html_record_facts')
    op.drop_index('ix_mfl_html_record_fact_dataset', table_name='mfl_html_record_facts')
    op.drop_table('mfl_html_record_facts')
    op.drop_index(op.f('ix_manual_player_mappings_source'), table_name='manual_player_mappings')
    op.drop_index(op.f('ix_manual_player_mappings_scraped_name'), table_name='manual_player_mappings')
    op.drop_index(op.f('ix_manual_player_mappings_id'), table_name='manual_player_mappings')
    op.drop_table('manual_player_mappings')
    op.drop_index(op.f('ix_league_settings_id'), table_name='league_settings')
    op.drop_table('league_settings')
    op.drop_index(op.f('ix_league_mfl_seasons_season'), table_name='league_mfl_seasons')
    op.drop_index(op.f('ix_league_mfl_seasons_league_id'), table_name='league_mfl_seasons')
    op.drop_index(op.f('ix_league_mfl_seasons_id'), table_name='league_mfl_seasons')
    op.drop_table('league_mfl_seasons')
    op.drop_index(op.f('ix_keeper_rules_id'), table_name='keeper_rules')
    op.drop_table('keeper_rules')
    op.drop_index(op.f('ix_draft_values_id'), table_name='draft_values')
    op.drop_table('draft_values')
    op.drop_index(op.f('ix_divisions_season'), table_name='divisions')
    op.drop_index(op.f('ix_divisions_id'), table_name='divisions')
    op.drop_table('divisions')
    op.drop_index(op.f('ix_unmatched_players_source'), table_name='unmatched_players')
    op.drop_index(op.f('ix_unmatched_players_scraped_name'), table_name='unmatched_players')
    op.drop_index(op.f('ix_unmatched_players_id'), table_name='unmatched_players')
    op.drop_table('unmatched_players')
    op.drop_index(op.f('ix_revoked_tokens_jti'), table_name='revoked_tokens')
    op.drop_index(op.f('ix_revoked_tokens_id'), table_name='revoked_tokens')
    op.drop_index('ix_revoked_tokens_expires_at', table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    op.drop_index(op.f('ix_positions_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_abbreviation'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_nfl_games_week'), table_name='nfl_games')
    op.drop_index(op.f('ix_nfl_games_season'), table_name='nfl_games')
    op.drop_index(op.f('ix_nfl_games_id'), table_name='nfl_games')
    op.drop_index(op.f('ix_nfl_games_event_id'), table_name='nfl_games')
    op.drop_table('nfl_games')
    op.drop_index(op.f('ix_manager_efficiency_week'), table_name='manager_efficiency')
    op.drop_index(op.f('ix_manager_efficiency_season'), table_name='manager_efficiency')
    op.drop_index(op.f('ix_manager_efficiency_manager_id'), table_name='manager_efficiency')
    op.drop_index(op.f('ix_manager_efficiency_league_id'), table_name='manager_efficiency')
    op.drop_index(op.f('ix_manager_efficiency_id'), table_name='manager_efficiency')
    op.drop_table('manager_efficiency')
    op.drop_index('ix_live_scoring_ingest_events_scope', table_name='live_scoring_ingest_events')
    op.drop_index(op.f('ix_live_scoring_ingest_events_id'), table_name='live_scoring_ingest_events')
    op.drop_index('ix_live_scoring_ingest_events_fingerprint', table_name='live_scoring_ingest_events')
    op.drop_table('live_scoring_ingest_events')
    op.drop_index(op.f('ix_leagues_name'), table_name='leagues')
    op.drop_index(op.f('ix_leagues_id'), table_name='leagues')
    op.drop_index(op.f('ix_leagues_current_season'), table_name='leagues')
    op.drop_table('leagues')
    op.drop_index('ix_canonical_player_snapshot_season', table_name='canonical_player_snapshots')
    op.drop_index('ix_canonical_player_snapshot_created', table_name='canonical_player_snapshots')
    op.drop_table('canonical_player_snapshots')
    # ### end Alembic commands ###
