
# Auto-generated by Alembic - fantasy-football-pi
"""
Revision ID: 0001_create_draft_value_tables
Revises: 
Create Date: 2026-02-21
"""

revision = '0001_create_draft_value_tables'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_id_mappings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('player_id', sa.Integer(), nullable=False),
        sa.Column('yahoo_id', sa.String(), nullable=True),
        sa.Column('espn_id', sa.String(), nullable=True),
        sa.Column('draftsharks_id', sa.String(), nullable=True),
        sa.Column('fantasypros_id', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_projections',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('player_id', sa.Integer(), nullable=True),
        sa.Column('source', sa.String(), nullable=False),
        sa.Column('season', sa.Integer(), nullable=False),
        sa.Column('projected_points', sa.Float(), nullable=True),
        sa.Column('adp', sa.Float(), nullable=True),
        sa.Column('auction_value', sa.Float(), nullable=True),
        sa.Column('position_rank', sa.Integer(), nullable=True),
        sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('draft_values',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('player_id', sa.Integer(), nullable=False),
        sa.Column('season', sa.Integer(), nullable=False),
        sa.Column('avg_auction_value', sa.Float(), nullable=True),
        sa.Column('median_adp', sa.Float(), nullable=True),
        sa.Column('consensus_tier', sa.String(), nullable=True),
        sa.Column('value_over_replacement', sa.Float(), nullable=True),
        sa.Column('last_updated', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('player_id', 'season', name='uq_draft_value_player_season')
    )
    op.create_table('manual_player_mappings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('source_name', sa.String(), nullable=False),
        sa.Column('scraped_player_name', sa.String(), nullable=False),
        sa.Column('true_player_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['true_player_id'], ['players.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    op.drop_table('manual_player_mappings')
    op.drop_table('draft_values')
    op.drop_table('platform_projections')
    op.drop_table('player_id_mappings')
