from __future__ import annotations

from pathlib import Path

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_AUTO_SHAPE_TYPE
from pptx.enum.shapes import MSO_SHAPE_TYPE
from pptx.util import Inches, Pt

ROOT = Path(__file__).resolve().parents[1]
PPTX_PATH = ROOT / 'docs' / 'uat' / 'uat_overview.pptx'
SCREENSHOT_DIR = (
    ROOT
    / 'frontend'
    / 'cypress'
    / 'screenshots'
    / 'uat_capture_pages.spec.js'
)

# Map deck slides to screenshot filenames generated by Cypress.
SLIDE_IMAGE_MAP: dict[int, str] = {
    4: 'uat_login_page.png',
    5: 'uat_home_page.png',
    6: 'uat_war_room_page.png',
    7: 'uat_chat_advisor_page.png',
    8: 'uat_draft_day_analyzer_page.png',
    9: 'uat_my_team_page.png',
    10: 'uat_matchups_page.png',
    11: 'uat_game_center_page.png',
    12: 'uat_waiver_wire_page.png',
    13: 'uat_keepers_page.png',
    14: 'uat_analytics_page.png',
    15: 'uat_playoff_bracket_page.png',
    16: 'uat_commissioner_dashboard_page.png',
    17: 'uat_commissioner_manage_owners_page.png',
    18: 'uat_commissioner_lineup_rules_page.png',
    19: 'uat_commissioner_waiver_rules_page.png',
    20: 'uat_commissioner_manage_trades_page.png',
    21: 'uat_commissioner_manage_divisions_page.png',
    22: 'uat_admin_settings_page.png',
    23: 'uat_bug_report_page.png',
}

# Fallback image box from the template dimensions.
DEFAULT_LEFT = Inches(0.75)
DEFAULT_TOP = Inches(1.49)
DEFAULT_WIDTH = Inches(7.82)
DEFAULT_HEIGHT = Inches(5.24)

MODAL_SLIDES: list[dict[str, object]] = [
    {
        'slide': 24,
        'title': 'Key Modals and Overlays',
        'image': 'uat_commissioner_draft_budgets_modal.png',
        'purpose': 'Highlight commissioner-only overlays required to configure draft controls.',
        'bullets': [
            'Set Draft Budgets modal is captured from Commissioner Dashboard.',
            'Slide validates visibility, legibility, and primary action placement.',
            'References: docs/ARCHITECTURE.md and docs/UI_REFERENCE.md.',
        ],
    },
    {
        'slide': 25,
        'title': 'Trade Proposal Modal',
        'image': 'uat_trade_proposal_modal.png',
        'purpose': 'Capture trade initiation controls before a proposal is submitted.',
        'bullets': [
            'Propose Trade modal validates manager, offered player, and requested player fields.',
            'Captures form controls and labels used by non-technical testers.',
            'Source workflow: /team from docs/API_PAGE_MATRIX.md.',
        ],
    },
    {
        'slide': 26,
        'title': 'Player Season Performance Modal',
        'image': 'uat_player_season_performance_modal.png',
        'purpose': 'Show player-level season details in the roster workflow.',
        'bullets': [
            'Season Performance modal is opened from roster player cards.',
            'Ensures detail cards and season metrics are visible and readable.',
            'Coverage aligns with docs/FRONTEND_UI_STANDARDS.md modal behavior.',
        ],
    },
    {
        'slide': 27,
        'title': 'Waiver Wire Modal Targets',
        'image': 'uat_waiver_confirm_modal.png',
        'purpose': 'Track waiver modal targets that are captured opportunistically based on route state.',
        'bullets': [
            'Waiver confirmation modal validates the explicit user approval step.',
            'Roster-full (drop player) overlay is captured in the screenshot runbook set.',
            'Use docs/UI_REFERENCE.md and docs/API_PAGE_MATRIX.md for workflow checks.',
        ],
    },
]

# Template text geometry
DECK_X, DECK_Y, DECK_W, DECK_H = Inches(0.6), Inches(0.12), Inches(7.2), Inches(0.28)
TITLE_X, TITLE_Y, TITLE_W, TITLE_H = Inches(0.6), Inches(0.45), Inches(7.4), Inches(0.5)
HEADER_X, HEADER_Y, HEADER_W, HEADER_H = Inches(0.6), Inches(1.00), Inches(12.2), Inches(0.4)
PURPOSE_HEAD_X, PURPOSE_HEAD_Y, PURPOSE_HEAD_W, PURPOSE_HEAD_H = Inches(8.72), Inches(1.54), Inches(4.29), Inches(0.39)
PURPOSE_BODY_X, PURPOSE_BODY_Y, PURPOSE_BODY_W, PURPOSE_BODY_H = Inches(8.95), Inches(2.02), Inches(3.95), Inches(1.45)
CORE_HEAD_X, CORE_HEAD_Y, CORE_HEAD_W, CORE_HEAD_H = Inches(8.72), Inches(3.82), Inches(4.29), Inches(0.39)
CORE_BODY_X, CORE_BODY_Y, CORE_BODY_W, CORE_BODY_H = Inches(8.95), Inches(4.28), Inches(3.95), Inches(2.05)

BLACK = RGBColor(0, 0, 0)
BORDER = RGBColor(18, 72, 98)


def find_or_make_picture_box(slide):
    """Return picture placeholder geometry; preserve existing picture position when present."""
    for shape in slide.shapes:
        if shape.shape_type == MSO_SHAPE_TYPE.PICTURE:
            return shape.left, shape.top, shape.width, shape.height, shape
    return DEFAULT_LEFT, DEFAULT_TOP, DEFAULT_WIDTH, DEFAULT_HEIGHT, None


def replace_slide_image(slide, image_path: Path) -> None:
    left, top, width, height, old_picture = find_or_make_picture_box(slide)

    if old_picture is not None:
        element = old_picture._element
        element.getparent().remove(element)

    slide.shapes.add_picture(str(image_path), left, top, width=width, height=height)


def ensure_slide_count(prs: Presentation, slide_number: int) -> None:
    blank_layout = prs.slide_layouts[6]
    while len(prs.slides) < slide_number:
        prs.slides.add_slide(blank_layout)


def remove_shape(shape) -> None:
    element = shape._element
    element.getparent().remove(element)


def clear_slide(slide) -> None:
    for shape in list(slide.shapes):
        remove_shape(shape)


def set_single_line_text(shape, text: str, size: int, bold: bool = False) -> None:
    tf = shape.text_frame
    tf.clear()
    p = tf.paragraphs[0]
    p.text = text
    if p.runs:
        run = p.runs[0]
        run.font.name = 'Aptos'
        run.font.size = Pt(size)
        run.font.bold = bold
        run.font.color.rgb = BLACK


def set_bullet_lines(shape, lines: list[str], size: int = 14) -> None:
    tf = shape.text_frame
    tf.clear()
    for index, line in enumerate(lines):
        p = tf.paragraphs[0] if index == 0 else tf.add_paragraph()
        p.text = f'- {line}'
        if p.runs:
            run = p.runs[0]
            run.font.name = 'Aptos'
            run.font.size = Pt(size)
            run.font.bold = False
            run.font.color.rgb = BLACK


def add_labeled_box(slide, left, top, width, height, label: str):
    box = slide.shapes.add_shape(MSO_AUTO_SHAPE_TYPE.RECTANGLE, left, top, width, height)
    box.fill.solid()
    box.fill.fore_color.rgb = RGBColor(255, 255, 255)
    box.line.color.rgb = BORDER
    set_single_line_text(box, label, 14, bold=False)
    return box


def upsert_modal_slide(
    prs: Presentation,
    *,
    slide_number: int,
    title: str,
    modal_image_path: Path,
    purpose_text: str,
    bullets: list[str],
) -> bool:
    ensure_slide_count(prs, slide_number)
    slide = prs.slides[slide_number - 1]
    clear_slide(slide)

    # Left image area
    if modal_image_path.exists():
        slide.shapes.add_picture(
            str(modal_image_path),
            DEFAULT_LEFT,
            DEFAULT_TOP,
            width=DEFAULT_WIDTH,
            height=DEFAULT_HEIGHT,
        )
        image_added = True
    else:
        image_added = False

    # Text structure matches other walkthrough slides
    deck_shape = slide.shapes.add_textbox(DECK_X, DECK_Y, DECK_W, DECK_H)
    set_single_line_text(deck_shape, 'PPL Insight Hub - UAT Overview', 18, bold=False)

    title_shape = slide.shapes.add_textbox(TITLE_X, TITLE_Y, TITLE_W, TITLE_H)
    set_single_line_text(title_shape, title, 28, bold=True)

    header_shape = slide.shapes.add_textbox(HEADER_X, HEADER_Y, HEADER_W, HEADER_H)
    set_single_line_text(
        header_shape,
        'Modal states are captured separately for workflows that require confirmation or admin actions.',
        18,
        bold=False,
    )

    add_labeled_box(slide, PURPOSE_HEAD_X, PURPOSE_HEAD_Y, PURPOSE_HEAD_W, PURPOSE_HEAD_H, 'PURPOSE')
    purpose_body = slide.shapes.add_textbox(PURPOSE_BODY_X, PURPOSE_BODY_Y, PURPOSE_BODY_W, PURPOSE_BODY_H)
    set_single_line_text(purpose_body, purpose_text, 14, bold=False)

    add_labeled_box(slide, CORE_HEAD_X, CORE_HEAD_Y, CORE_HEAD_W, CORE_HEAD_H, 'CORE FUNCTIONALITY')
    core_body = slide.shapes.add_textbox(CORE_BODY_X, CORE_BODY_Y, CORE_BODY_W, CORE_BODY_H)
    set_bullet_lines(core_body, bullets, size=14)

    return image_added


def main() -> int:
    if not PPTX_PATH.exists():
        print(f'Missing deck: {PPTX_PATH}')
        return 1

    if not SCREENSHOT_DIR.exists():
        print(f'Missing screenshot directory: {SCREENSHOT_DIR}')
        return 1

    prs = Presentation(PPTX_PATH)

    applied = 0
    missing_files: list[str] = []

    for slide_number, screenshot_name in SLIDE_IMAGE_MAP.items():
        screenshot_path = SCREENSHOT_DIR / screenshot_name
        if not screenshot_path.exists():
            missing_files.append(screenshot_name)
            continue

        ensure_slide_count(prs, slide_number)
        slide = prs.slides[slide_number - 1]
        replace_slide_image(slide, screenshot_path)
        applied += 1

    for modal_slide in MODAL_SLIDES:
        image_name = str(modal_slide['image'])
        modal_image_path = SCREENSHOT_DIR / image_name
        image_added = upsert_modal_slide(
            prs,
            slide_number=int(modal_slide['slide']),
            title=str(modal_slide['title']),
            modal_image_path=modal_image_path,
            purpose_text=str(modal_slide['purpose']),
            bullets=[str(item) for item in modal_slide['bullets']],
        )
        if image_added:
            applied += 1
        else:
            missing_files.append(image_name)

    prs.save(PPTX_PATH)

    print(f'Updated slide images: {applied}')
    if missing_files:
        print('Missing screenshots:')
        for item in missing_files:
            print(f' - {item}')

    return 0


if __name__ == '__main__':
    raise SystemExit(main())
